package com.exam.EmpSystem.mapp;


import com.exam.EmpSystem.dto.DesignationDto;
import com.exam.EmpSystem.entity.Designation;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface DesignationMapper {


    DesignationMapper INSTANCE = Mappers.getMapper(DesignationMapper.class);

    @Mapping(target = "id", ignore = true) // Ignore mapping id from DTO to Entity since it's autogenerated
    Designation dtoToEntity(DesignationDto dto);

    DesignationDto entityToDto(Designation entity);
}
