package com.exam.EmpSystem.mapp;


import com.exam.EmpSystem.dto.GradeDto;
import com.exam.EmpSystem.entity.Grade;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface GradeMapper {

    GradeMapper INSTANCE = Mappers.getMapper(GradeMapper.class);

    @Mapping(target = "id", ignore = true) // Since ID is generated by the database, we ignore it during mapping
    Grade dtoToEntity(GradeDto gradeDto);

    GradeDto entityToDto(Grade grade);
}
